# Generated by Django 3.1.1 on 2020-09-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='img',
            field=models.ImageField(upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='price',
            field=models.ImageField(upload_to=''),
        ),
    ]
